version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'
